### ISSUE TITLE
Not working on macOS Ventura 13.0.1. 

### ISSUE THREAD

**Issue by jerik** [wayneyaoo/alfred-cheat#30]
Hi. I updated my System to Ventura. On my previous macOS Version it worked. 

What I observed. Ventura seems to have droped the default installation of python2. I had already installed python3 on my system, so I made a symbolic link to it 

    /usr/local/bin/python -> ../Cellar/python@3.10/3.10.6_2/bin/python3

But this did not help. When I run in Alfred4 ``cf ~/cheat`` I get an error message in the Alfred4.workflow.bug-console

	[22:30:01.108] Cheat[Keyword] Processing complete
	[22:30:01.117] Cheat[Keyword] Passing output '~/cheat' to Run Script
	[22:30:01.184] ERROR: Cheat[Run Script] /bin/bash: python: command not found

Afterwards, when I try to run ``cheat foo`` I get the following message in Alfred4.workflow.bug-console

	[22:30:45.376] Cheat[Script Filter] Queuing argument '(null)'
	[22:30:45.386] Cheat[Script Filter] Script with argv '(null)' finished
	[22:30:45.388] ERROR: Cheat[Script Filter] Code 127: Exited with error code but no message

any ideas to solve the problem?

**Comment by jerik** [comment]
I tried to change all term ``python`` to ``python3`` in the workflow editor, but this raised just another issue. 

run ``cf ~/cheat`` in Alfred
Alfred.workflow.bug-console: 
	[22:47:57.764] Cheat[Keyword] Processing complete
	[22:47:57.765] Cheat[Keyword] Passing output '~/cheat' to Run Script
	[22:47:57.927] ERROR: Cheat[Run Script] Traceback (most recent call last):
	  File "config.py", line 4, in <module>
		from workflow import Workflow3 as Workflow
	  File "/Users/jerik/workspace/alfred/Alfred.alfredpreferences/workflows/user.workflow.640C53A2-54B0-4D2B-91A2-70FA177D119D/workflow/__init__.py", line 16, in <module>
		from .workflow import Workflow, manager
	  File "/Users/jerik/workspace/alfred/Alfred.alfredpreferences/workflows/user.workflow.640C53A2-54B0-4D2B-91A2-70FA177D119D/workflow/workflow.py", line 25, in <module>
		import cPickle
	ModuleNotFoundError: No module named 'cPickle'

**Comment by wayneyaoo** [comment]
@jerik which version of the workflow are you using? Latest release of 1.2.1 should support OS version without py2.

**Comment by jerik** [comment]
Thanks. Works fine with 1.2.1. I had the issues with 1.2.0.
